# Generated by Django 3.0.5 on 2020-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_service_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="contact_phone_details",
            field=models.TextField(
                blank=True,
                verbose_name="Le details du numéro de téléphone (horaires, prix, ...)",
            ),
        ),
    ]
