# Generated by Django 3.0.5 on 2020-04-28 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_create_service_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=300, verbose_name="Le nom de la source de donnée"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Plus de détails sur la source de donnée",
                        verbose_name="Une description",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=32, verbose_name="Le type de source"),
                ),
                (
                    "dataset_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        verbose_name="L'adresse où l'on peut trouver le jeu de donnée",
                    ),
                ),
                (
                    "contact_website_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        verbose_name="L'adresse du site internet",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        verbose_name="L'adresse du logo de la source de donnée",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="La date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="La date de dernière modification"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="data_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="core.DataSource",
            ),
        ),
    ]
