# Generated by Django 3.0.5 on 2020-04-30 10:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_data_source_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="legal_entity_type",
            field=models.CharField(
                choices=[
                    ("association", "Association"),
                    ("collectivite", "Collectivité locale ou territoriale"),
                    ("cae", "Coopérative d'Activités et d'Entrepreneur·es (CAE)"),
                    (
                        "epci",
                        "Établissement public de coopération intercommunale (EPCI)",
                    ),
                    (
                        "epic",
                        "Établissement public à caractère industriel et commercial (EPIC)",
                    ),
                    (
                        "epscp",
                        "Établissement public à caractère scientifique, culturel et professionnel (EPSCP)",
                    ),
                    ("gip", "Groupement d'intérêt public (GIP)"),
                    ("sas", "Société par actions simplifiée (SAS)"),
                    ("sarl", "Société à responsabilité limitée (SARL)"),
                    ("sasu", "Société par actions simplifiée unipersonnelle (SASU)"),
                    ("scic", "société coopérative d’intérêt collectif (SCIC)"),
                    ("scop", "Société coopérative et participative (SCOP)"),
                    ("spl", "Société publique locale (SPL)"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                max_length=32,
                verbose_name="La nature juridique du lieu",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="import_comment",
            field=models.TextField(
                blank=True,
                verbose_name="Informations complémentaires sur l'import de la donnée",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="import_config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                null=True,
                verbose_name="Information et configuration de l'import de la donnée",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="dataset_local_path",
            field=models.CharField(
                default="",
                max_length=300,
                verbose_name="Le chemin d'accès au jeu de donnée",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasource",
            name="dataset_last_updated",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="La date de dernière mise à jour du jeu de donnée",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="dataset_name",
            field=models.CharField(
                default="", max_length=300, verbose_name="Le nom du jeu de donnée"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(
                max_length=300, verbose_name="Le nom du fournisseur de donnée"
            ),
        ),
    ]
