# Generated by Django 3.0.5 on 2020-04-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_place_contact_phone_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="https://beta.gouv.fr/img/logo_twitter_image-2019.jpg",
                max_length=300,
                verbose_name="L'adresse du logo du lieu",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="legal_entity_type",
            field=models.CharField(
                choices=[
                    ("association", "Association"),
                    ("collectivite", "Collectivité locale ou territoriale"),
                    ("cae", "Coopérative d'Activités et d'Entrepreneur·es (CAE)"),
                    (
                        "epci",
                        "Établissement public de coopération intercommunale (EPCI)",
                    ),
                    (
                        "epscp",
                        "Établissement public à caractère scientifique, culturel et professionnel (EPSCP)",
                    ),
                    ("sas", "Société par actions simplifiée (SAS)"),
                    ("sarl", "Société à responsabilité limitée (SARL)"),
                    ("sasu", "Société par actions simplifiée unipersonnelle (SASU)"),
                    ("scic", "société coopérative d’intérêt collectif (SCIC)"),
                    ("scop", "Société coopérative et participative (SCOP)"),
                    ("spl", "Société publique locale (SPL)"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                max_length=32,
                verbose_name="La nature juridique du lieu",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="data_source",
            field=models.CharField(
                default="autre",
                help_text="Hub 123",
                max_length=300,
                verbose_name="La source de donnée",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="data_source",
            field=models.CharField(
                default="autre",
                help_text="Hub 123",
                max_length=300,
                verbose_name="La source de donnée",
            ),
            preserve_default=False,
        ),
    ]
