# Generated by Django 3.0.5 on 2020-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20200430_1209"),
    ]

    operations = [
        migrations.RemoveField(model_name="service", name="has_label_mfs",),
        migrations.AddField(
            model_name="place",
            name="has_label_fs",
            field=models.BooleanField(
                default=False, verbose_name="Labellisé France Service"
            ),
        ),
    ]
