# Generated by Django 3.0.5 on 2020-07-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200504_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="contact_website_url",
            field=models.URLField(
                blank=True,
                max_length=300,
                verbose_name="L'adresse du site internet de la source de donnée",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datasource", unique_together={("name", "dataset_name")},
        ),
    ]
