# Generated by Django 3.0.5 on 2020-09-11 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20200709_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="target_audience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("tout public", "Tout public"),
                        ("allocataire", "Allocataires"),
                        ("demandeur emploi", "Demandeurs d'emploi"),
                        ("etranger", "Étrangers"),
                        ("famille", "Familles"),
                        ("jeune", "-25 ans, Jeunes"),
                        ("handicap", "Personnes en situation de handicap"),
                        ("senior", "Séniors"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Public cible",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration - Collectivité territoriale"),
                    ("association", "Association"),
                    ("bibliotheque", "Bibliothèque - Médiathèque"),
                    ("commune", "Commune (Ville, CCAS, Centre Culturel...)"),
                    ("centre social", "Centre social"),
                    ("departement", "Département (UTPAS, MDS, MDSI, UTAS...)"),
                    ("formation", "Organisme de formations"),
                    ("intercommunalite", "Intercommunalité (EPCI)"),
                    ("la poste", "La Poste"),
                    ("maison quartier", "Maison de quartier"),
                    ("msap", "Maison de Service au Public (MSAP)"),
                    ("pole emploi", "Pôle Emploi"),
                    ("pimms", "Point Information Médiation Multi Services (PIMMS)"),
                    ("prefecture", "Préfecture, Sous-Préfecture"),
                    (
                        "securite sociale",
                        "Organisme de sécurité sociale (CAF, CPAM, CARSAT, MSA...)",
                    ),
                    ("tiers lieu", "Tiers-lieu & coworking, FabLab"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                help_text="Administration",
                max_length=32,
                verbose_name="La typologie du lieu",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="target_audience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("tout public", "Tout public"),
                        ("allocataire", "Allocataires"),
                        ("demandeur emploi", "Demandeurs d'emploi"),
                        ("etranger", "Étrangers"),
                        ("famille", "Familles"),
                        ("jeune", "-25 ans, Jeunes"),
                        ("handicap", "Personnes en situation de handicap"),
                        ("senior", "Séniors"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Public cible (s'il est différent du public cible du lieu)",
            ),
        ),
    ]
