# Generated by Django 3.0.5 on 2020-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20200911_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration - Collectivité territoriale"),
                    ("association", "Association"),
                    ("bibliotheque", "Bibliothèque - Médiathèque"),
                    ("commune", "Commune (Ville, CCAS, Centre Culturel...)"),
                    ("centre social", "Centre social"),
                    ("departement", "Département (UTPAS, MDS, MDSI, UTAS...)"),
                    ("epn", "Espace Public Numérique (EPN)"),
                    ("formation", "Organisme de formations"),
                    ("intercommunalite", "Intercommunalité (EPCI)"),
                    ("la poste", "La Poste"),
                    ("maison quartier", "Maison de quartier"),
                    ("msap", "Maison de Service au Public (MSAP)"),
                    ("pole emploi", "Pôle Emploi"),
                    ("pimms", "Point Information Médiation Multi Services (PIMMS)"),
                    ("prefecture", "Préfecture, Sous-Préfecture"),
                    (
                        "securite sociale",
                        "Organisme de sécurité sociale (CAF, CPAM, CARSAT, MSA...)",
                    ),
                    ("tiers lieu", "Tiers-lieu & coworking, FabLab"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                help_text="Administration",
                max_length=32,
                verbose_name="La typologie du lieu",
            ),
        ),
    ]
