# Generated by Django 3.0.5 on 2020-09-16 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200916_1253"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_free",
            field=models.BooleanField(
                default=True, verbose_name="Le lieu est-il gratuit ?"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="opening_hours_details",
            field=models.TextField(
                blank=True,
                help_text="sur rendez-vous le Mardi, porte-ouvertes le Mercredi, ...",
                verbose_name="Des détails supplémentaires sur les horaires d'ouverture",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="price_details",
            field=models.TextField(
                blank=True, verbose_name="Le details des prix du lieu"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="support_access",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("libre", "Accès libre"),
                        ("inscription", "Sur inscription ou rendez-vous"),
                        ("public cible", "Public cible uniquement"),
                        ("adherent", "Adhérents uniquement"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="libre, inscription, adherent, ...",
                size=None,
                verbose_name="Modalité(s) d'accès",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="support_access_raw",
            field=models.TextField(blank=True, verbose_name="Modalité(s) d'accès brut"),
        ),
        migrations.AddField(
            model_name="place",
            name="support_mode",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("individuel", "Individuel, Personnalisé"),
                        ("collectif", "Collectif"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="individuel, collectif, ...",
                size=None,
                verbose_name="Modalité(s) d'accompagnement",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="support_mode_raw",
            field=models.TextField(
                blank=True, verbose_name="Modalité(s) d'accompagnement brut"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="opening_hours_raw",
            field=models.TextField(
                blank=True,
                help_text="Du lundi au vendredi de 8h à 20h",
                verbose_name="Les horaires d'ouverture brut",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="target_audience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("tout public", "Tout public"),
                        ("allocataire", "Allocataires"),
                        ("demandeur emploi", "Demandeurs d'emploi"),
                        ("etranger", "Étrangers"),
                        ("famille", "Familles"),
                        ("jeune", "-25 ans, Jeunes"),
                        ("handicap", "Personnes en situation de handicap"),
                        ("senior", "Séniors"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="tout public, jeune, senior, allocataire, etranger, ...",
                size=None,
                verbose_name="Public(s) cible",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="target_audience_raw",
            field=models.TextField(blank=True, verbose_name="Public(s) cible brut"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_details",
            field=models.TextField(
                blank=True, verbose_name="Le details des prix du service"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="support_access",
            field=models.CharField(
                blank=True,
                choices=[
                    ("libre", "Accès libre"),
                    ("inscription", "Sur inscription ou rendez-vous"),
                    ("public cible", "Public cible uniquement"),
                    ("adherent", "Adhérents uniquement"),
                ],
                help_text="libre, inscription, adherent, ...",
                max_length=32,
                verbose_name="Modalités d'accès (si différent du lieu)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="support_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individuel", "Individuel, Personnalisé"),
                    ("collectif", "Collectif"),
                ],
                help_text="individuel, collectif, ...",
                max_length=32,
                verbose_name="Modalités d'accompagnement (si différent du lieu)",
            ),
        ),
    ]
