# Generated by Django 3.0.5 on 2020-09-17 14:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_improve_arrayfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="exemple@email.fr",
                max_length=150,
                verbose_name="Le courriel",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="contact_website_url",
            field=models.URLField(
                blank=True,
                help_text="https://www.example.fr",
                max_length=300,
                verbose_name="L'adresse du site internet de la source de donnée",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="https://www.example.fr/logo.png",
                max_length=300,
                verbose_name="L'adresse du logo de la source de donnée",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="type",
            field=models.CharField(
                choices=[
                    ("hub", "Hub"),
                    ("national", "National"),
                    ("region", "Région"),
                    ("departement", "Département"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                max_length=32,
                verbose_name="Le type de source",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="contact_facebook_url",
            field=models.URLField(
                blank=True,
                help_text="https://www.facebook.com/",
                max_length=300,
                verbose_name="L'adresse de la page Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="contact_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="https://www.youtube.com/user/example",
                max_length=300,
                verbose_name="L'adresse de la page Youtube",
            ),
        ),
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=300, verbose_name="Le nom du jeu de donnée"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=300,
                        verbose_name="L'adresse où l'on peut trouver le jeu de donnée",
                    ),
                ),
                (
                    "local_path",
                    models.CharField(
                        max_length=300,
                        verbose_name="Le chemin d'accès au jeu de donnée",
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="La date de dernière mise à jour du jeu de donnée",
                    ),
                ),
                (
                    "import_config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Information et configuration de l'import de la donnée",
                    ),
                ),
                (
                    "import_comment",
                    models.TextField(
                        blank=True,
                        verbose_name="Informations complémentaires sur l'import de la donnée",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="La date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="La date de dernière modification"
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_sets",
                        to="core.DataSource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="data_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="core.DataSet",
            ),
        ),
    ]
