# Generated by Django 3.0.5 on 2020-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_create_data_set_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="place", name="data_source",),
        migrations.AlterUniqueTogether(name="datasource", unique_together=set(),),
        migrations.AddConstraint(
            model_name="datasource",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique data source name"
            ),
        ),
        migrations.RemoveField(model_name="datasource", name="dataset_last_updated",),
        migrations.RemoveField(model_name="datasource", name="dataset_local_path",),
        migrations.RemoveField(model_name="datasource", name="dataset_name",),
        migrations.RemoveField(model_name="datasource", name="dataset_url",),
        migrations.RemoveField(model_name="datasource", name="import_comment",),
        migrations.RemoveField(model_name="datasource", name="import_config",),
    ]
