# Generated by Django 3.0.5 on 2020-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_cleanup_data_source_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="opening_hours_osm_format",
            field=models.CharField(
                blank=True,
                help_text="Mo-Fr 8:00-20:00",
                max_length=300,
                verbose_name="Les horaires d'ouverture au format OpenStreetMap",
            ),
        ),
    ]
