# Generated by Django 3.0.5 on 2020-10-08 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20200930_1933"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="legal_entity_type",
            field=models.CharField(
                choices=[
                    ("association", "Association"),
                    ("collectivite", "Collectivité locale ou territoriale"),
                    ("cae", "Coopérative d'Activités et d'Entrepreneur·es (CAE)"),
                    (
                        "epci",
                        "Établissement public de coopération intercommunale (EPCI)",
                    ),
                    (
                        "epic",
                        "Établissement public à caractère industriel et commercial (EPIC)",
                    ),
                    (
                        "epscp",
                        "Établissement public à caractère scientifique, culturel et professionnel (EPSCP)",
                    ),
                    ("gip", "Groupement d'intérêt public (GIP)"),
                    ("sas", "Société par actions simplifiée (SAS)"),
                    ("sarl", "Société à responsabilité limitée (SARL)"),
                    ("sasu", "Société par actions simplifiée unipersonnelle (SASU)"),
                    ("scic", "Société coopérative d’intérêt collectif (SCIC)"),
                    ("scop", "Société coopérative et participative (SCOP)"),
                    ("spl", "Société publique locale (SPL)"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                max_length=32,
                verbose_name="La nature juridique du lieu",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="siret",
            field=models.CharField(
                blank=True,
                max_length=14,
                verbose_name="Identifiant INSEE de l'établissement ou de l'entreprise (SIRET)",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("prive", "Privé"),
                    ("public-prive", "Public - Privé"),
                    ("autre", "Autre, Inconnu"),
                ],
                default="autre",
                help_text="Public",
                max_length=32,
                verbose_name="Le statut du lieu",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="target_audience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("tout public", "Tout public"),
                        ("allocataire", "Allocataires"),
                        ("demandeur emploi", "Demandeurs d'emploi"),
                        ("etranger", "Étrangers"),
                        ("famille", "Familles"),
                        ("jeune", "Jeunes"),
                        ("handicap", "Personnes en situation de handicap"),
                        ("senior", "Séniors"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="tout public, jeune, senior, allocataire, etranger, ...",
                size=None,
                verbose_name="Public(s) cible",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="target_audience",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("tout public", "Tout public"),
                        ("allocataire", "Allocataires"),
                        ("demandeur emploi", "Demandeurs d'emploi"),
                        ("etranger", "Étrangers"),
                        ("famille", "Familles"),
                        ("jeune", "Jeunes"),
                        ("handicap", "Personnes en situation de handicap"),
                        ("senior", "Séniors"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Public cible (s'il est différent du public cible du lieu)",
            ),
        ),
    ]
