# Generated by Django 3.0.5 on 2020-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20201116_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[
                    (
                        "Accès à un équipement informatique",
                        "Accès à un équipement informatique",
                    ),
                    (
                        "Accompagnement aux démarches administratives en ligne",
                        "Accompagnement aux démarches administratives en ligne",
                    ),
                    (
                        "Évaluation de compétences numériques",
                        "Évaluation de compétences numériques",
                    ),
                    (
                        "Acquisition de compétences numériques",
                        "Acquisition de compétences numériques",
                    ),
                    (
                        "Vente de matériel informatique",
                        "Vente de matériel informatique",
                    ),
                    ("Stockage numérique sécurisé", "Stockage numérique sécurisé"),
                    (
                        "Pratiquer des activités récréatives numériques",
                        "Pratiquer des activités récréatives numériques",
                    ),
                ],
                max_length=300,
                verbose_name="Le nom du service",
            ),
        ),
    ]
