HUBS = []

CHOICE_OTHER = "autre"

PLACE_TYPE_CHOICES = [
    ("centre social", "Centre social"),
    ("securite sociale", "Organisme de sécurité sociale (CAF, CPAM, CARSAT, MSA...)",),
    ("tiers lieu", "Tiers-lieu & coworking, FabLab"),
    ("association", "Association"),
    ("maison quartier", "Maison de quartier"),
    ("pimms", "Point Information Médiation Multi Services (PIMMS)"),
    ("msap", "Maison de Service au Public (MSAP)"),
    ("bibliotheque", "Bibliothèque - Médiathèque"),
    ("formation", "Organisme de formations"),
    ("pole emploi", "Pôle Emploi"),
    ("commune", "Commune (Ville, CCAS, Centre Culturel...)"),
    ("intercommunalite", "Intercommunalité (EPCI)"),
    ("administration", "Administration - Collectivité territoriale"),
    ("departement", "Département (UTPAS, MDS, MDSI, UTAS...)"),
    ("prefecture", "Préfecture, Sous-Préfecture"),
    (CHOICE_OTHER, "Autre, Inconnu"),
]

PLACE_STATUS_CHOICES = [
    ("public", "Public"),
    ("prive", "Privé"),
    ("public-prive", "Public / Privé"),
    (CHOICE_OTHER, "Autre, Inconnu"),
]

PLACE_LEGAL_ENTITY_TYPE_CHOICES = [
    ("association", "Association"),
    ("collectivite", "Collectivité locale ou territoriale"),
    ("cae", "Coopérative d'Activités et d'Entrepreneur·es (CAE)"),
    ("epci", "Établissement public de coopération intercommunale (EPCI)"),
    ("sasu", "Société par actions simplifiée unipersonnelle (SASU)"),
    ("scic", "société coopérative d’intérêt collectif (SCIC)"),
    ("scop", "Société coopérative et participative (SCOP)"),
    ("spl", "Société publique locale (SPL)"),
    (CHOICE_OTHER, "Autre, Inconnu"),
]

TARGET_AUDIENCE_CHOICES = [
    ("tout public", "Tout public"),
    ("-25 ans", "-25 ans, Jeune"),
    ("senior", "Sénior"),
    ("demandeur emploi", "Demandeur d'emploi"),
    ("famille", "Famille"),
    ("allocataire", "Allocataires"),
]

LANGUAGE_CHOICES = [
    ("fr", "Français"),
    ("en", "Anglais"),
    ("fsl", "Language des signes"),
]

PAYMENT_CHOICES = [
    ("especes", "Espèces"),
    ("carte bancaire", "Carte bancaire"),
    ("cheque", "Chèque"),
    ("aptic", "Chèque APTIC"),
    ("cif", "Congé individuel de formation (CIF)"),
    # "CRP",
    # "AFPE"
]

EQUIPMENT_CHOICES = [
    ("wifi", "WiFi"),
    ("ordinateur", "Ordinateur"),
    ("scanner", "Scanner"),
    ("imprimante", "Imprimante"),
    # "Autre"
]
HANDICAP_CHOICES = [
    ("handicap moteur", "Handicap moteur"),
    ("handicap visuel", "Handicap visuel"),
    ("handicap auditif", "Handicap auditif"),
    ("handicap mental", "Handicap intellectuel ou psychique"),
    # "Maladie invalidante",
    # "Mobilité limitée"
]

SERVICE_NAME_LIST = [
    "Accès à un équipement informatique",
    "Accompagnement aux démarches administratives en ligne",
    "Acquisition de compétences numériques",
    "Vente de matériel informatique",
    "Stockage numérique sécurisé",
]

SERVICE_SUPPORT_ACCESS_CHOICES = [
    ("libre", "Accès libre"),
    ("inscription", "Sur inscription ou rendez-vous"),
    ("public cible", "Public cible uniquement"),
    ("adherents", "Adhérents uniquement"),
]
SERVICE_SUPPORT_MODE_CHOICES = [
    ("individuel", "Individuel, Personnalisé"),
    ("collectif", "Collectif"),
]

FRANCE_REGION_LIST = [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Bretagne",
    "Centre-Val de Loire",
    "Corse",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandie",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
    "Guadeloupe",
    "Martinique",
    "Guyane",
    "La Réunion",
    "Mayotte",
]

FRANCE_DEPARTEMENT_CHOICES = [
    ("Ain", "Ain (01)"),
    ("Aisne", "Aisne (02)"),
    ("Allier", "Allier (03)"),
    ("Alpes-de-Haute-Provence", "Alpes-de-Haute-Provence (04)"),
    ("Hautes-Alpes", "Hautes-Alpes (05)"),
    ("Alpes-Maritimes", "Alpes-Maritimes (06)"),
    ("Ardèche", "Ardèche (07)"),
    ("Ardennes", "Ardennes (08)"),
    ("Ariège", "Ariège (09)"),
    ("Aube", "Aube (10)"),
    ("Aude", "Aude (11)"),
    ("Aveyron", "Aveyron (12)"),
    ("Bouches-du-Rhône", "Bouches-du-Rhône (13)"),
    ("Calvados", "Calvados (14)"),
    ("Cantal", "Cantal (15)"),
    ("Charente", "Charente (16)"),
    ("Charente-Maritime", "Charente-Maritime (17)"),
    ("Cher", "Cher (18)"),
    ("Corrèze", "Corrèze (19)"),
    ("Côte-d'Or", "Côte-d'Or (21)"),
    ("Côtes-d'Armor", "Côtes-d'Armor (22)"),
    ("Creuse", "Creuse (23)"),
    ("Dordogne", "Dordogne (24)"),
    ("Doubs", "Doubs (25)"),
    ("Drôme", "Drôme (26)"),
    ("Eure", "Eure (27)"),
    ("Eure-et-Loir", "Eure-et-Loir (28)"),
    ("Finistère", "Finistère (29)"),
    ("Corse-du-Sud", "Corse-du-Sud (2A)"),
    ("Haute-Corse", "Haute-Corse (2B)"),
    ("Gard", "Gard (30)"),
    ("Haute-Garonne", "Haute-Garonne (31)"),
    ("Gers", "Gers (32)"),
    ("Gironde", "Gironde (33)"),
    ("Hérault", "Hérault (34)"),
    ("Ille-et-Vilaine", "Ille-et-Vilaine (35)"),
    ("Indre", "Indre (36)"),
    ("Indre-et-Loire", "Indre-et-Loire (37)"),
    ("Isère", "Isère (38)"),
    ("Jura", "Jura (39)"),
    ("Landes", "Landes (40)"),
    ("Loir-et-Cher", "Loir-et-Cher (41)"),
    ("Loire", "Loire (42)"),
    ("Haute-Loire", "Haute-Loire (43)"),
    ("Loire-Atlantique", "Loire-Atlantique (44)"),
    ("Loiret", "Loiret (45)"),
    ("Lot", "Lot (46)"),
    ("Lot-et-Garonne", "Lot-et-Garonne (47)"),
    ("Lozère", "Lozère (48)"),
    ("Maine-et-Loire", "Maine-et-Loire (49)"),
    ("Manche", "Manche (50)"),
    ("Marne", "Marne (51)"),
    ("Haute-Marne", "Haute-Marne (52)"),
    ("Mayenne", "Mayenne (53)"),
    ("Meurthe-et-Moselle", "Meurthe-et-Moselle (54)"),
    ("Meuse", "Meuse (55)"),
    ("Morbihan", "Morbihan (56)"),
    ("Moselle", "Moselle (57)"),
    ("Nièvre", "Nièvre (58)"),
    ("Nord", "Nord (59)"),
    ("Oise", "Oise (60)"),
    ("Orne", "Orne (61)"),
    ("Pas-de-Calais", "Pas-de-Calais (62)"),
    ("Puy-de-Dôme", "Puy-de-Dôme (63)"),
    ("Pyrénées-Atlantiques", "Pyrénées-Atlantiques (64)"),
    ("Hautes-Pyrénées", "Hautes-Pyrénées (65)"),
    ("Pyrénées-Orientales", "Pyrénées-Orientales (66)"),
    ("Bas-Rhin", "Bas-Rhin (67)"),
    ("Haut-Rhin", "Haut-Rhin (68)"),
    ("Rhône", "Rhône (69)"),
    ("Haute-Saône", "Haute-Saône (70)"),
    ("Saône-et-Loire", "Saône-et-Loire (71)"),
    ("Sarthe", "Sarthe (72)"),
    ("Savoie", "Savoie (73)"),
    ("Haute-Savoie", "Haute-Savoie (74)"),
    ("Seine-Maritime", "Seine-Maritime (76)"),
    ("Seine-et-Marne", "Seine-et-Marne (77)"),
    ("Yvelines", "Yvelines (78)"),
    ("Deux-Sèvres", "Deux-Sèvres (79)"),
    ("Somme", "Somme (80)"),
    ("Tarn", "Tarn (81)"),
    ("Tarn-et-Garonne", "Tarn-et-Garonne (82)"),
    ("Var", "Var (83)"),
    ("Vaucluse", "Vaucluse (84)"),
    ("Vendée", "Vendée (85)"),
    ("Vienne", "Vienne (86)"),
    ("Haute-Vienne", "Haute-Vienne (87)"),
    ("Vosges", "Vosges (88)"),
    ("Yonne", "Yonne (89)"),
    ("Territoire de Belfort", "Territoire de Belfort (90)"),
    ("Essonne", "Essonne (91)"),
    ("Hauts-de-Seine", "Hauts-de-Seine (92)"),
    ("Seine-Saint-Denis", "Seine-Saint-Denis (93)"),
    ("Val-de-Marne", "Val-de-Marne (94)"),
    ("Val-d'Oise", "Val-d'Oise (95)"),
    ("Guadeloupe", "Guadeloupe (971)"),
    ("Martinique", "Martinique (972)"),
    ("Guyane", "Guyane (973)"),
    ("La Réunion", "La Réunion (974)"),
    ("Mayotte", "Mayotte (976)"),
]
