# Generated by Django 3.0.5 on 2020-04-14 16:40

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="BetaGouv",
                        max_length=300,
                        verbose_name="Le nom du lieu",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="L'incubateur de Services Numériques de l'État",
                        verbose_name="Une description du lieu",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("centre social", "Centre social"),
                            (
                                "securite sociale",
                                "Organisme de sécurité sociale (CAF, CPAM, CARSAT, MSA...)",
                            ),
                            ("tiers lieu", "Tiers-lieu & coworking, FabLab"),
                            ("association", "Association"),
                            ("maison quartier", "Maison de quartier"),
                            (
                                "pimms",
                                "Point Information Médiation Multi Services (PIMMS)",
                            ),
                            ("msap", "Maison de Service au Public (MSAP)"),
                            ("bibliotheque", "Bibliothèque - Médiathèque"),
                            ("formation", "Organisme de formations"),
                            ("pole emploi", "Pôle Emploi"),
                            ("commune", "Commune (Ville, CCAS, Centre Culturel...)"),
                            ("intercommunalite", "Intercommunalité (EPCI)"),
                            (
                                "administration",
                                "Administration - Collectivité territoriale",
                            ),
                            ("departement", "Département (UTPAS, MDS, MDSI, UTAS...)"),
                            ("prefecture", "Préfecture, Sous-Préfecture"),
                            ("autre", "Autre, Inconnu"),
                        ],
                        default="autre",
                        help_text="Administration",
                        max_length=32,
                        verbose_name="La typologie du lieu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("prive", "Privé"),
                            ("public-prive", "Public / Privé"),
                            ("autre", "Autre, Inconnu"),
                        ],
                        default="autre",
                        help_text="Public",
                        max_length=32,
                        verbose_name="Le statut du lieu",
                    ),
                ),
                (
                    "address_raw",
                    models.CharField(
                        help_text="20 Avenue de Ségur 75007 Paris",
                        max_length=300,
                        verbose_name="L'adresse complète",
                    ),
                ),
                (
                    "address_housenumber",
                    models.CharField(
                        blank=True,
                        help_text="20",
                        max_length=5,
                        verbose_name="Le numéro avec indice de répétition éventuel (bis, ter, A, B)",
                    ),
                ),
                (
                    "address_street",
                    models.CharField(
                        blank=True,
                        help_text="Avenue de Ségur",
                        max_length=150,
                        verbose_name="Le nom de la rue",
                    ),
                ),
                (
                    "address_postcode",
                    models.CharField(
                        blank=True,
                        help_text="75007",
                        max_length=5,
                        verbose_name="Le code postal",
                    ),
                ),
                (
                    "address_citycode",
                    models.CharField(
                        blank=True,
                        help_text="75107",
                        max_length=5,
                        verbose_name="Le code INSEE de la commune",
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True,
                        help_text="Paris",
                        max_length=150,
                        verbose_name="Le nom de la commune",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="48.850699",
                        null=True,
                        verbose_name="La latitude (coordonnée géographique)",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="2.308628",
                        null=True,
                        verbose_name="La longitude (coordonnée géographique)",
                    ),
                ),
                (
                    "is_itinerant",
                    models.BooleanField(
                        default=False, verbose_name="Le lieu est-il itinérant ?"
                    ),
                ),
                (
                    "contact_phone_raw",
                    models.CharField(
                        max_length=300, verbose_name="Le numéro de téléphone brut"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="0123456789",
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="le numéro de téléphone doit être au format 0123456789",
                                regex="^[0-9]{10}$",
                            )
                        ],
                        verbose_name="Le numéro de téléphone",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="exemple@email.fr",
                        max_length=150,
                        verbose_name="Le courriel",
                    ),
                ),
                (
                    "contact_website",
                    models.URLField(
                        blank=True,
                        help_text="https://beta.gouv.fr/",
                        max_length=300,
                        verbose_name="L'adresse du site internet",
                    ),
                ),
                (
                    "opening_hours_raw",
                    models.TextField(
                        blank=True,
                        help_text="Du lundi au vendredi de 8h à 20h",
                        verbose_name="Les horaires d'ouverture",
                    ),
                ),
                (
                    "opening_hours_osm_format",
                    models.CharField(
                        blank=True,
                        help_text="Mo-Fr 8:00-20:00",
                        max_length=150,
                        verbose_name="Les horaires d'ouverture au format OpenStreetMap",
                    ),
                ),
                (
                    "has_equipment_wifi",
                    models.BooleanField(default=False, verbose_name="WiFi"),
                ),
                (
                    "has_equipment_computer",
                    models.BooleanField(default=False, verbose_name="Ordinateur"),
                ),
                (
                    "has_equipment_scanner",
                    models.BooleanField(default=False, verbose_name="Scanner"),
                ),
                (
                    "has_equipment_printer",
                    models.BooleanField(default=False, verbose_name="Imprimante"),
                ),
                (
                    "equipment_other",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Autres équipements disponibles",
                    ),
                ),
                (
                    "has_accessibility_hi",
                    models.BooleanField(default=False, verbose_name="Handicap auditif"),
                ),
                (
                    "has_accessibility_mi",
                    models.BooleanField(default=False, verbose_name="Handicap moteur"),
                ),
                (
                    "has_accessibility_pi",
                    models.BooleanField(
                        default=False, verbose_name="Handicap intellectuel ou psychique"
                    ),
                ),
                (
                    "has_accessibility_vi",
                    models.BooleanField(default=False, verbose_name="Handicap visuel"),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Français, Anglais, ...",
                        max_length=150,
                        verbose_name="Langues parlées",
                    ),
                ),
                (
                    "payment_methods",
                    models.CharField(
                        blank=True,
                        help_text="Espèces, Carte Bancaire, ...",
                        max_length=150,
                        verbose_name="Les moyens de paiement",
                    ),
                ),
                (
                    "additional_information",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Informations additionnelles stockées au format JSON",
                    ),
                ),
                (
                    "osm_node_id",
                    models.IntegerField(
                        blank=True,
                        help_text="5266052428",
                        null=True,
                        verbose_name="OpenStreetMap node id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="La date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="La date de dernière modification"
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
    ]
