# Generated by Django 3.0.4 on 2020-04-03 13:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_carto_api', '0002_create_service_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='itinerant',
            new_name='is_itinerant',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price_free',
            new_name='is_free',
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='', help_text='Le nom du service', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='address_raw',
            field=models.CharField(help_text="L'adresse complète", max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Une description du service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='label_other',
            field=models.CharField(blank=True, help_text='Autres labels', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_methods',
            field=models.CharField(blank=True, help_text='Les moyens de paiements spécifiques à ce service', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_detail',
            field=models.CharField(blank=True, help_text='Le details des prix', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='public_target',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('tout public', 'Tout public'), ('-25 ans', '-25 ans'), ('senior', 'Sénior'), ('demandeur emploi', "Demandeur d'emploi"), ('famille', 'Famille')], max_length=32), blank=True, default=list, help_text='Public cible', size=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='schedule_hours_raw',
            field=models.CharField(blank=True, help_text='Les horaires du service', max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='siret',
            field=models.CharField(blank=True, help_text='Coordonnées juridiques (SIRET)', max_length=14),
        ),
    ]
