# Generated by Django 3.0.4 on 2020-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidants_connect_carto_api', '0003_auto_20200403_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='accessibility_hi',
            new_name='has_accessibility_hi',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='accessibility_mi',
            new_name='has_accessibility_mi',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='accessibility_pi',
            new_name='has_accessibility_pi',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='accessibility_vi',
            new_name='has_accessibility_vi',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='equipement_computer',
            new_name='has_equipement_computer',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='equipement_printer',
            new_name='has_equipement_printer',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='equipement_scanner',
            new_name='has_equipement_scanner',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='equipement_wifi',
            new_name='has_equipement_wifi',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='label_aidants_connect',
            new_name='has_label_aidants_connect',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='label_mfs',
            new_name='has_label_mfs',
        ),
        migrations.AlterField(
            model_name='place',
            name='contact_website',
            field=models.URLField(blank=True, help_text="L'adresse du site internet", max_length=150),
        ),
    ]
